spring:
  application:
    name: TechBazaar-REST
  datasource:
    url: jdbc:mysql://localhost:3306/techbazaar??useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: '@MeRk998#_'
    username: 'root'
    driver-class-name: com.mysql.cj.jdbc.Driver